@call cl.exe ^
src/all_in_one.cc ^
src/imgui/imgui_demo.cpp ^
src/imgui/imgui_draw.cpp ^
src/imgui/imgui_impl_glfw.cpp ^
src/imgui/imgui_impl_opengl3.cpp ^
src/imgui/imgui_impl_win32.cpp ^
src/imgui/imgui_impl_dx11.cpp ^
src/imgui/imgui_tables.cpp ^
src/imgui/imgui_widgets.cpp ^
src/imgui/imgui_stdlib.cpp ^
src/imgui/imgui.cpp ^
src/libs/stb_image.cpp ^
resource/swan.res ^
/Fo:obj_release\ ^
/Fe:dist/swan_release.exe ^
/Fd:dist/vc140_release.pdb ^
/I"C:/code/glfw" ^
/I"C:/code/glew-2.1.0" ^
/I"C:/code/boost_1_80_0" ^
/std:c++20 ^
/nologo ^
/W4 ^
/EHsc ^
/O2 ^
/MT ^
/D_CRT_SECURE_NO_WARNINGS ^
/DNDEBUG ^
/link ^
/SUBSYSTEM:WINDOWS ^
/NODEFAULTLIB:MSVCRTD ^
/NODEFAULTLIB:LIBCMT ^
/LIBPATH:"C:/code/glfw" ^
/LIBPATH:"C:/code/glew-2.1.0" ^
/LIBPATH:"C:/code/boost_1_80_0/stage/lib" ^
glfw3.lib ^
opengl32.lib ^
glew32s.lib ^
gdi32.lib ^
shell32.lib ^
kernel32.lib ^
msvcrt.lib ^
ole32.lib ^
shlwapi.lib ^
Pathcch.lib ^
Dbghelp.lib ^
D3D11.lib
