// Single translation unit compilation nearly doubles compile speed.
// Precompiled header (stdafx.hpp) offers another 3x speed increase.

#include "stdafx.hpp"

#include "bulk_rename_logic.cpp"
#include "debug_log.cpp"
#include "explorer.cpp"
#include "explorer_file_op_progress_sink.cpp"
#include "file_operations.cpp"
#include "finder.cpp"
#include "focused_window.cpp"
#include "icon_browser.cpp"
#include "icon_glyphs.cpp"
#include "icon_library.cpp"
#include "imgui_dependent_functions.cpp"
#include "imgui_extension.cpp"
#include "miscellaneous_functions.cpp"
#include "miscellaneous_globals.cpp"
#include "path.cpp"
#include "pinned.cpp"
#include "popup_modal_bulk_rename.cpp"
#include "popup_modal_edit_pin.cpp"
#include "popup_modal_error.cpp"
#include "popup_modal_new_directory.cpp"
#include "popup_modal_new_file.cpp"
#include "popup_modal_new_pin.cpp"
#include "popup_modal_single_rename.cpp"
#include "popup_modal_open_state_tracker.cpp"
#include "recent_files.cpp"
#include "retired.cpp"
#include "settings.cpp"
#include "stdafx.cpp"
#include "style.cpp"
#include "swan.cpp"
#include "theme_editor.cpp"
#include "undelete_directory_progress_sink.cpp"
#include "util.cpp"
