// This nearly doubles compile speed lol (from >6 seconds to ~3.5 seconds)

#include "bulk_rnm_mdl.cpp"
#include "bulk_rnm.cpp"
#include "debug_log.cpp"
#include "error_mdl.cpp"
#include "explorer.cpp"
#include "file_ops.cpp"
#include "focused_wndw.cpp"
#include "misc_options.cpp"
#include "misc.cpp"
#include "path.cpp"
#include "pins_mgr.cpp"
#include "sngl_rnm_mdl.cpp"
#include "style.cpp"
#include "swan.cpp"
#include "util.cpp"
#include "wndw_opts.cpp"
