// Single translation unit compilation nearly doubles compile speed.
// Precompiled header (stdafx.hpp) offers another 3x speed increase.

#include "stdafx.hpp"

#include "bulk_rnm_mdl.cpp"
#include "bulk_rnm.cpp"
#include "debug_log.cpp"
#include "edit_pin_mdl.cpp"
#include "error_mdl.cpp"
#include "explorer.cpp"
#include "file_ops.cpp"
#include "focused_wndw.cpp"
#include "icon_browser.cpp"
#include "icons.cpp"
#include "imgui_ext.cpp"
#include "imgui_specific.cpp"
#include "misc.cpp"
#include "new_pin_mdl.cpp"
#include "path.cpp"
#include "pin_mgr.cpp"
#include "recent_files.cpp"
#include "settings.cpp"
#include "sngl_rnm_mdl.cpp"
#include "style.cpp"
#include "swan.cpp"
#include "und_dir_prog_snk.cpp"
#include "util.cpp"
#include "xpl_file_op_prog_snk.cpp"
